const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.jumpthru,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.LOS,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.GamePush_Channels,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAddScore,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerScore,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.CompareOrientation,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.LeaderboardEachPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerIndex,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchScoped
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Твинанимация: 0},
	{Player: 0},
	{Jumpthru: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{ПолеЗрения: 0},
	{Platform2: 0},
	{Якорь: 0},
	{ТайловыйФон: 0},
	{WhiteSkull2ndOutline256px: 0},
	{CloseButton1st64px: 0},
	{CheckmarkButton1st64px: 0},
	{Bomb: 0},
	{BombEffect: 0},
	{Score_txt: 0},
	{ЛокальноеХранилище: 0},
	{GamePush: 0},
	{GamePushChannels: 0},
	{PlayerIcon: 0},
	{MaxScore_txt: 0},
	{TelegramS_txt: 0},
	{StartY: 0},
	{Перетаскивание: 0},
	{Scroll: 0},
	{ScrollText: 0},
	{Text: 0},
	{leadername_txt: 0},
	{leaderbalance_txt: 0},
	{leaderid_txt: 0},
	{RecordLid_Icon: 0},
	{Fon1: 0},
	{Fon2: 0},
	{Аудио: 0},
	{MinScroll: 0},
	{NextPlatform: 0},
	{MaxScore: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Platform2: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	WhiteSkull2ndOutline256px: class extends self.ISpriteInstance {},
	CloseButton1st64px: class extends self.ISpriteInstance {},
	CheckmarkButton1st64px: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	BombEffect: class extends self.ISpriteInstance {},
	Score_txt: class extends self.ITextInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	GamePushChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	PlayerIcon: class extends self.ISpriteInstance {},
	MaxScore_txt: class extends self.ITextInstance {},
	TelegramS_txt: class extends self.ITextInstance {},
	Scroll: class extends self.ISpriteInstance {},
	ScrollText: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	leadername_txt: class extends self.ITextInstance {},
	leaderbalance_txt: class extends self.ITextInstance {},
	leaderid_txt: class extends self.ITextInstance {},
	RecordLid_Icon: class extends self.ISpriteInstance {},
	Fon1: class extends self.ITiledBackgroundInstance {},
	Fon2: class extends self.ITiledBackgroundInstance {},
	Аудио: class extends self.IInstance {}
}